/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Traveling;

import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author INVALID
 */
public class TravelInterface extends javax.swing.JFrame {
    double Gross;
    cFlight cost = new cFlight();
    /**
     * Creates new form TravelInterface
     */
    public TravelInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTxtFull = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtAdd = new javax.swing.JTextField();
        jtxtGen = new javax.swing.JTextField();
        jtxtNation = new javax.swing.JTextField();
        jtxtCont = new javax.swing.JTextField();
        jtxtPass = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jrbStandard = new javax.swing.JRadioButton();
        jrbFirstClass = new javax.swing.JRadioButton();
        jrbSingle = new javax.swing.JRadioButton();
        jrbEconomy = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jrbReturn = new javax.swing.JRadioButton();
        jlblSingle = new javax.swing.JLabel();
        jlblReturn = new javax.swing.JLabel();
        jlblStandard = new javax.swing.JLabel();
        jlblFirstClass = new javax.swing.JLabel();
        jlblEconomy = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jcmbAcc = new javax.swing.JComboBox();
        jcmbDeparture = new javax.swing.JComboBox();
        jcmbDestination = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jLabel1.setBackground(new java.awt.Color(153, 102, 255));
        jLabel1.setFont(new java.awt.Font("Cooper Black", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Travel Managment System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-traveler-64.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-travel-card-64 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Full Name ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        jTxtFull.setBackground(new java.awt.Color(204, 204, 255));
        jTxtFull.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTxtFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFullActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtFull, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 38, 250, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Address");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-more-details-48.png"))); // NOI18N
        jLabel6.setText(" Customer Details ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 260, 30));

        jtxtDob.setBackground(new java.awt.Color(204, 204, 255));
        jtxtDob.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDobActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 250, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Gender ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Nationality ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Contact No. ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Email ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Passport No. ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Date of Birth");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 30));

        jtxtAdd.setBackground(new java.awt.Color(204, 204, 255));
        jtxtAdd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 250, 30));

        jtxtGen.setBackground(new java.awt.Color(204, 204, 255));
        jtxtGen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jtxtGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 250, 30));

        jtxtNation.setBackground(new java.awt.Color(204, 204, 255));
        jtxtNation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jtxtNation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 250, -1));

        jtxtCont.setBackground(new java.awt.Color(204, 204, 255));
        jtxtCont.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jtxtCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 250, -1));

        jtxtPass.setBackground(new java.awt.Color(204, 204, 255));
        jtxtPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jtxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 250, -1));

        jtxtEmail.setBackground(new java.awt.Color(204, 204, 255));
        jtxtEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 250, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 410, 360));

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbStandard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbStandard.setText("Standard");
        jrbStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbStandardActionPerformed(evt);
            }
        });
        jPanel3.add(jrbStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, -1));

        jrbFirstClass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbFirstClass.setText("First Class");
        jrbFirstClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFirstClassActionPerformed(evt);
            }
        });
        jPanel3.add(jrbFirstClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, -1));

        jrbSingle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbSingle.setText("Single");
        jrbSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSingleActionPerformed(evt);
            }
        });
        jPanel3.add(jrbSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 90, -1));

        jrbEconomy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbEconomy.setText("Economy");
        jrbEconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEconomyActionPerformed(evt);
            }
        });
        jPanel3.add(jrbEconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        jCheckBox1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jCheckBox1.setText("Special Needs");
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, 40));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-info-64.png"))); // NOI18N
        jLabel23.setText("Ticket and Hotel Information");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 40));

        jrbReturn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jrbReturn.setText("Return");
        jrbReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbReturnActionPerformed(evt);
            }
        });
        jPanel3.add(jrbReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 90, -1));

        jlblSingle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblSingle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSingle.setText("0");
        jlblSingle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        jPanel3.add(jlblSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 100, 30));

        jlblReturn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblReturn.setText("0");
        jlblReturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        jPanel3.add(jlblReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 100, 30));

        jlblStandard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblStandard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblStandard.setText("0");
        jlblStandard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        jPanel3.add(jlblStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, 30));

        jlblFirstClass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblFirstClass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblFirstClass.setText("0");
        jlblFirstClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        jPanel3.add(jlblFirstClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, 30));

        jlblEconomy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblEconomy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblEconomy.setText("0");
        jlblEconomy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 2));
        jPanel3.add(jlblEconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 450, 260));

        jPanel4.setBackground(new java.awt.Color(153, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-hotel-40.png"))); // NOI18N
        jLabel17.setText("Accomodation");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 50));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-treasure-map-40.png"))); // NOI18N
        jLabel18.setText(" Destination");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 50));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-airplane-take-off-64.png"))); // NOI18N
        jLabel19.setText("Departure");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 50));

        jCheckBox2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jCheckBox2.setText("Airport Tax");
        jPanel4.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));

        jCheckBox3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jCheckBox3.setText("Air Mile Over 20000");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 210, -1));

        jCheckBox4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jCheckBox4.setText("Extra Luggage");
        jPanel4.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 210, -1));

        jCheckBox5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jCheckBox5.setText("Traveling Insurance");
        jPanel4.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jcmbAcc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcmbAcc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Belmond Grand Hotel Timeo,Italy", "The Lanesborough,London", "The Beekman,NYC", "Taj Diplomatic Enclave,New Delhi", "Raffles,Singapore", "The Alpina, Switzerland", "Palace Hotel, Tokyo", "Taj,Bangalor,India", "Le Meurice,Paris", "Redison Blu,Bangladesh", "La Meridan,Bangladesh", "Ruposhi Bangla,Bangladesh", " ", " ", " ", " " }));
        jPanel4.add(jcmbAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 290, -1));

        jcmbDeparture.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcmbDeparture.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Bangladesh", "Norway", "Paris", "Singapore Changi Airport", "Tokyo Haneda Airport", "Dubai Airport", "San Francisco International Airport" }));
        jPanel4.add(jcmbDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 68, 290, 30));

        jcmbDestination.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcmbDestination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Canada - 7 Days in Torrnto", "Canada - 7 Days in Ottawa", "Norway - 7 Days in Oslo", "Nigeria - 7 Days in Lagos Elco Atlantic", "India -  5 Days in New Delih", "Italy - 5 Days in Rome", "USA - 5 Days in Alsaka", "UK - 5 Days in London", "France - 5 Days in Parisi", "Kenya - 5 Days in Nairobi", "Ghana - 5 Days in Acora", "South Africa - 5 Days in Cape Town", "Bangladesh - 5 Days in Cox's Bazar", " " }));
        jcmbDestination.setEnabled(false);
        jcmbDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDestinationActionPerformed(evt);
            }
        });
        jPanel4.add(jcmbDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 290, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-travel-visa-50.png"))); // NOI18N
        jLabel24.setText("Travel Information");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 530, 360));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Stencil", 1, 22)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("R e c e i p t ");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Montserrat Subrayada", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 340, 510));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 340, 550));

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setBackground(new java.awt.Color(204, 255, 255));
        jbtnExit.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jbtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-cancel-64.png"))); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 160, 50));

        jbtnTotal.setBackground(new java.awt.Color(204, 255, 255));
        jbtnTotal.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jbtnTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-plus-64.png"))); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 50));

        jbtnReset.setBackground(new java.awt.Color(204, 255, 255));
        jbtnReset.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jbtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-synchronize-64.png"))); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 180, 50));

        jbtnReceipt.setBackground(new java.awt.Color(204, 255, 255));
        jbtnReceipt.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jbtnReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-purchase-order-64.png"))); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.setToolTipText("");
        jbtnReceipt.setAutoscrolls(true);
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 200, 50));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, 830, 70));

        jPanel5.setBackground(new java.awt.Color(153, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traveling/icons8-estimate-40.png"))); // NOI18N
        jLabel25.setText("Price Calculation");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 40));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Tax");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setText("Total");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 100, 30));

        jlblTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jlblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 230, 40));

        jlblSubTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jlblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 230, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 490, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFullActionPerformed

    private void jtxtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDobActionPerformed

    private void jtxtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAddActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        cQuit cExit = new cQuit();
        cExit.quit();
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        // TODO add your handling code here:
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        String iTime = (tTime.format(timer.getTime()));
        
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        String iDate = (Tdate.format(timer.getTime()));
        
        int num1;
        String ref = "";
        num1 = 1325 + (int) (Math.random()*4238);
        ref+= num1+1325;
        
        //===========================================
        String Fullname = (jTxtFull.getText());
        String Birth = (jtxtDob.getText());
        String Address = (jtxtAdd.getText());
        String Gender = (jtxtGen.getText());
        String Nationality = (jtxtNation.getText());
        String Contact = (jtxtCont.getText());
        String Email = (jtxtEmail.getText());
        String Passport = (jtxtPass.getText());
        String Tax = (jlblTotal.getText());
        String Total = (jlblSubTotal.getText());
        
        jTextArea1.append("\tTravels Managment System\n\n"
                +"Ref:\t\t" + ref 
                +"\n-------------------------------------"
                +"\nFirst Name:\t\t"+ Fullname
                +"\nDate of Birth:\t\t"+ Birth
                +"\nAddress:\t\t"+ Address
                +"\nGender:\t\t"+ Gender
                +"\nNationality\t\t"+ Nationality
                +"\nContact\t\t"+ Contact
                +"\nEmail\t\t"+ Email
                +"\nPassport No.\t\t"+ Passport
                +"\nTax:\t\t"+ Tax
                +"\nTotal\t\t"+ Total
                +"\n--------------------------------------"
                +"\nDate:" + iDate + "\tTime:"+iTime
                +"\n\n\t Thanks For Using\n\t    kmhm Travel Managment system"
        
     
        );

        
        
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jrbStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbStandardActionPerformed
        // TODO add your handling code here:
        if(jrbStandard.isSelected() == true){
            jcmbDestination.setEnabled(true);
            jrbFirstClass.setSelected(false);
            jrbEconomy.setSelected(false);
            jlblFirstClass.setText("0");
            jlblEconomy.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
            
        }
         if(jrbStandard.isSelected() == false){
            jcmbDestination.getSelectedItem().equals("None");
            jcmbDestination.setEnabled(false);
            jlblStandard.setText("0");
        }
        
    }//GEN-LAST:event_jrbStandardActionPerformed

    private void jrbFirstClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFirstClassActionPerformed
        // TODO add your handling code here:
        if(jrbFirstClass.isSelected() == true){
            jcmbDestination.setEnabled(true);
            jrbStandard.setSelected(false);
            jrbEconomy.setSelected(false);
            jlblStandard.setText("0");
            jlblEconomy.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
            
        }
         if(jrbFirstClass.isSelected() == false){
            jcmbDestination.getSelectedItem().equals("None");
            jcmbDestination.setEnabled(false);
            jlblFirstClass.setText("0");
        }
        
    }//GEN-LAST:event_jrbFirstClassActionPerformed

    private void jrbSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSingleActionPerformed

    private void jrbEconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEconomyActionPerformed
        // TODO add your handling code here:
        
        if(jrbEconomy.isSelected() == true){
            jcmbDestination.setEnabled(true);
            jrbFirstClass.setSelected(false);
            jrbStandard.setSelected(false);
            jlblFirstClass.setText("0");
            jlblEconomy.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
            
        }
         if(jrbEconomy.isSelected() == false){
            jcmbDestination.getSelectedItem().equals("None");
            jcmbDestination.setEnabled(false);
            jlblEconomy.setText("0");
        }
    }//GEN-LAST:event_jrbEconomyActionPerformed

    private void jrbReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbReturnActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        
        
        cCostTax iTax  = new cCostTax();
        
        double iTaxes, subtotal;
        
        if(jrbReturn.isSelected()){
            subtotal = Gross * 2;
            String isubtotal = String.format("$%.2f",subtotal );
            
            jlblSubTotal.setText(isubtotal);
            iTaxes = iTax.cFindTax(subtotal);
            String Tax = String.format("$%.2f",iTaxes);
            jlblTotal.setText(Tax);
            
                        
            String iTotal = String.format("$%.2f",(subtotal+iTaxes));
            jlblTotal.setText(iTotal);
            
            
            jlblReturn.setText(isubtotal);
            
        }
        else{
            subtotal = Gross;
            String isubtotal = String.format("$%.2f",subtotal);
            
            jlblSubTotal.setText(isubtotal);
            iTaxes = iTax.cFindTax(subtotal);
            String Tax = String.format("$%.2f",iTaxes);
            jlblTotal.setText(Tax);
            
                        
            String iTotal = String.format("$%.2f",(subtotal + iTaxes));
            jlblTotal.setText(iTotal);
            
        }

        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jcmbDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDestinationActionPerformed
// TODO add your handling code here:
        //canada - 7 days in torronto
        
        if((jcmbDestination.getSelectedItem().equals("Canada - 7 Days in Torrnto")) && jrbStandard.isSelected()){
            Gross = cost.Canada_Torrent;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        
        //Canada - 7 Days in Ottawa
        if((jcmbDestination.getSelectedItem().equals("Canada - 7 Days in Ottawa")) && jrbStandard.isSelected()){
            Gross = cost.Canada_O;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Norway - 7 Days in Oslo
        if((jcmbDestination.getSelectedItem().equals("Norway - 7 Days in Oslo")) && jrbStandard.isSelected()){
            Gross = cost.Norway;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Nigeria - 7 Days in Lagos Elco Atlantic
        if((jcmbDestination.getSelectedItem().equals("Nigeria - 7 Days in Lagos Elco Atlantic")) && jrbStandard.isSelected()){
            Gross = cost.Nigeria;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //India -  5 Days in New Delih
        if((jcmbDestination.getSelectedItem().equals("India -  5 Days in New Delih")) && jrbStandard.isSelected()){
            Gross = cost.India;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Italy - 5 Days in Rome
        if((jcmbDestination.getSelectedItem().equals("Italy - 5 Days in Rome")) && jrbStandard.isSelected()){
            Gross = cost.Italy;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //USA - 5 Days in Alsaka
        if((jcmbDestination.getSelectedItem().equals("USA - 5 Days in Alsaka")) && jrbStandard.isSelected()){
            Gross = cost.USA;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //UK - 5 Days in London
        if((jcmbDestination.getSelectedItem().equals("UK - 5 Days in London")) && jrbStandard.isSelected()){
            Gross = cost.UK_London;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //France - 5 Days in Paris
        if((jcmbDestination.getSelectedItem().equals("France - 5 Days in Paris")) && jrbStandard.isSelected()){
            Gross = cost.France;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Kenya - 5 Days in Nairobi
        if((jcmbDestination.getSelectedItem().equals("Kenya - 5 Days in Nairobi")) && jrbStandard.isSelected()){
            Gross = cost.Kenya;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Ghana - 5 Days in Acora
        if((jcmbDestination.getSelectedItem().equals("Ghana - 5 Days in Acora")) && jrbStandard.isSelected()){
            Gross = cost.Ghana;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //South Africa - 5 Days in Cape Town
        if((jcmbDestination.getSelectedItem().equals("South Africa - 5 Days in Cape Town")) && jrbStandard.isSelected()){
            Gross = cost.South_Afira;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Bangladesh - 5 Days in Cox's Bazar
        if((jcmbDestination.getSelectedItem().equals("Bangladesh - 5 Days in Cox's Bazar")) && jrbStandard.isSelected()){
            Gross = cost.Bangladesh;
            String Cost = String.format("$%.2f",Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        
        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        //economy class
        if((jcmbDestination.getSelectedItem().equals("Bangladesh - 5 Days in Cox's Bazar")) && jrbEconomy.isSelected()){
            Gross = cost.Bangladesh;
            String Cost = String.format("$%.2f",Gross + 350);
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        
        if((jcmbDestination.getSelectedItem().equals("France - 5 Days in Paris")) && jrbEconomy.isSelected()){
            Gross = cost.France;
            String Cost = String.format("$%.2f",Gross + 350);
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Kenya - 5 Days in Nairobi
        if((jcmbDestination.getSelectedItem().equals("Kenya - 5 Days in Nairobi")) && jrbEconomy.isSelected()){
            Gross = cost.Kenya;
            String Cost = String.format("$%.2f",Gross + 350);
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Ghana - 5 Days in Acora
        if((jcmbDestination.getSelectedItem().equals("Ghana - 5 Days in Acora")) && jrbEconomy.isSelected()){
            Gross = cost.Ghana;
            String Cost = String.format("$%.2f",Gross + 350);
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        
        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
       //First class
        if((jcmbDestination.getSelectedItem().equals("Nigeria - 7 Days in Lagos Elco Atlantic")) && jrbFirstClass.isSelected()){
            Gross = cost.Nigeria;
            String Cost = String.format("$%.2f",Gross + 200);
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //India -  5 Days in New Delih
        if((jcmbDestination.getSelectedItem().equals("India -  5 Days in New Delih")) && jrbFirstClass.isSelected()){
            Gross = cost.India;
            String Cost = String.format("$%.2f",Gross + 200);
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //Italy - 5 Days in Rome
        if((jcmbDestination.getSelectedItem().equals("Italy - 5 Days in Rome")) && jrbFirstClass.isSelected()){
            Gross = cost.Italy;
            String Cost = String.format("$%.2f",Gross + 200);
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        
        
    }//GEN-LAST:event_jcmbDestinationActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jTxtFull.setText(null);
        jtxtAdd.setText(null);
        jtxtGen.setText(null);
        jtxtDob.setText(null);
        jtxtNation.setText(null);
        jtxtCont.setText(null);
        jtxtEmail.setText(null);
        jtxtPass.setText(null);
        jlblTotal.setText(null);
        jlblSubTotal.setText(null);
        jlblTotal.setText(null);
        jcmbAcc.setSelectedItem("None");
        jcmbDeparture.setSelectedItem("None");
        jcmbDestination.setSelectedItem("None");
        jlblStandard.setText(null);
        jlblFirstClass.setText(null);
        jlblEconomy.setText(null);
        jlblReturn.setText(null);
        jlblSingle.setText(null);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtFull;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JComboBox jcmbAcc;
    private javax.swing.JComboBox jcmbDeparture;
    private javax.swing.JComboBox jcmbDestination;
    private javax.swing.JLabel jlblEconomy;
    private javax.swing.JLabel jlblFirstClass;
    private javax.swing.JLabel jlblReturn;
    private javax.swing.JLabel jlblSingle;
    private javax.swing.JLabel jlblStandard;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JRadioButton jrbEconomy;
    private javax.swing.JRadioButton jrbFirstClass;
    private javax.swing.JRadioButton jrbReturn;
    private javax.swing.JRadioButton jrbSingle;
    private javax.swing.JRadioButton jrbStandard;
    private javax.swing.JTextField jtxtAdd;
    private javax.swing.JTextField jtxtCont;
    private javax.swing.JTextField jtxtDob;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtGen;
    private javax.swing.JTextField jtxtNation;
    private javax.swing.JTextField jtxtPass;
    // End of variables declaration//GEN-END:variables
}
